apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "http-ingress.name" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.hosts.http }}
    http:
      paths:
{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: "/"
        backend:
          serviceName:  {{ template "fullname" . }}-http
          servicePort: {{ .Values.service.http.port }}
{{- else }}
      - path: "/" 
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "fullname" . }}-http
            port:
              number: {{ .Values.service.http.port }}     
{{- end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.ingress.hosts.http }}"
    secretName: {{ .Values.ingress.tls.secret.httpSecretName }}
{{- end }}
