apiVersion: v1
kind: Secret
metadata:
  name: {{ template "db.fullname" . }}
  labels:
    app: {{ template "postgres.name" . }}
    chart: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dbPassword:  {{ .Values.postgres.postgresPassword | b64enc | quote }}
